[build]
builder = "DOCKERFILE"
dockerfilePath = "open-tgate/Dockerfile.api"

[deploy]
healthcheckPath = "/healthz"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

